WEATHER_BUTTON_CALLBACK_DATA = 'weather'
NOTIFICATION_BUTTON_CALLBACK_DATA = 'notification'

WEATHER_BUTTON_LABEL = "Weather"
NOTIFICATION_BUTTON_LABEL = "Notification"

NOTIFICATION_MORNING_CALLBACK_DATA = 'morning'
NOTIFICATION_EVENING_CALLBACK_DATA = 'evening'
DISABLE_NOTIFICATION_CALLBACK_DATA = 'disable_notifications'

NOTIFICATION_MORNING_LABEL = "Every morning"
NOTIFICATION_EVENING_LABEL = "Every evening"
NOTIFICATION_DISABLE_LABEL = "Disable notifications"
